### ISSUE TITLE
Docker "ds-cv-inference" build issues

### ISSUE THREAD

**Issue by afarodrigues** [intel-iot-devkit/automated-checkout#1]
After execute "make build" as described on documentation, the following problems are happening. 

This script installs the following OpenVINO 3rd-party dependencies:
  1. GTK+ and GStreamer libraries used by OpenCV
  2. libusb library required for Myriad plugin for Inference Engine
  3. Python 3.6 for Model Optimizer
  4. gcc 4.8.5 and other build dependencies for OpenVINO samples
  5. build dependencies for GStreamer Plugins

/opt/intel/openvino_2020.4.287/install_dependencies/install_openvino_dependencies.sh: line 258: yum: command not found
The command '/bin/sh -c $INSTALL_DIR/install_dependencies/install_openvino_dependencies.sh' returned a non-zero code: 127
Makefile:9: recipe for target 'build' failed
make[1]: *** [build] Error 127
make[1]: Leaving directory '/home/andre/workspace/softex/automated-checkout/ds-cv-inference'
Makefile:63: recipe for target 'ds-cv-inference' failed
make: *** [ds-cv-inference] Error 2

**Comment by antoniomtz** [comment]
It is fixed now. Thanks for the report.
