### ISSUE TITLE
Logging only be seen in main, other parts of code also need to add logging info

### ISSUE THREAD

**Issue by vli11** [intel-iot-devkit/automated-checkout#10]

**Comment by joshua-silverio** [comment]
@vli11 @brian-intel It looks like the device services already have and use logging clients do we still want to add more or are those sufficient for those services? I added to the ms folders in the two pr's above.

**Comment by brian-intel** [comment]
@joshua-silverio The logging is only required in ms-inventory and ms-authentication. Since the routes code was new we were unsure how to use the logging client which is why it was missing. All other services should have proper logging.

**Comment by joshua-silverio** [comment]
closed by #30 and #31
