### ISSUE TITLE
Fix document link

### ISSUE THREAD

**Issue by brian-intel** [intel-iot-devkit/automated-checkout#24]

**Comment by lenny-intel** [comment]
I think this broke when I renamed `master` to `main`. I verified the settings are correct. i.e. using main for the pages.

**Comment by lenny-intel** [comment]
@brian-intel , there is workflow to rebuild the GitHub Pages. I reran it and the link is good now.

We will need to rerun it again when we merge all the changes back to main.

I think we can close this issue now.
